Us/13: Add Event in Calendar from DayView/WeekView page
kb-dev/UKit pull request #25
Opened 2021-07-23 09:14 UTC by thclmnt

Allow application to access calendar to add event from long pressing a class in DayView & WeekView page.

Notable changes:
- Added permissions for Android & iOS in app.json
- Added a long press event in CourseRow component
- Created a new modal/popup with new translations to confirm wanting to add event to calendar
- Handled app permissions to trigger only when user wants to add an event
- Added Toast to notify if event was successfully added to calendar or not
- Fixed a bug for Toast not working properly without `react-native-root-siblings` package in newer versions of React Native

2021-07-27 13:10 UTC, AamuLumi requested changes

2021-07-27 13:10 UTC, AamuLumi commented on utils/translations/fr.js
> +		'Voulez vous filtrer cette UE? Vous pouvez toujours annuler cette action dans les paramètres.',
**Voulez-vous filter cette UE ? ...**

2021-07-27 13:10 UTC, AamuLumi commented on utils/translations/fr.js
> +		"L'application a besoin des permissions pour ajouter des événement au calendrier",
**pour ajouter des événements au ...**

2021-07-27 13:16 UTC, thclmnt commented on utils/translations/fr.js
> +		'Voulez vous filtrer cette UE? Vous pouvez toujours annuler cette action dans les paramètres.',
done

2021-07-27 13:16 UTC, thclmnt commented on utils/translations/fr.js
> +		"L'application a besoin des permissions pour ajouter des événement au calendrier",
done

2021-07-28 14:52 UTC, AamuLumi approved these changes

2021-07-28 14:52 UTC, merged